project:
  type: website
  output-dir: _site

profile:
  default: en
  group:
    - [en, ca, es]

website:
  title: "José C. Milisenda"
  favicon: assets/favicon.png
  page-footer:
    center: "© 2026 José César Milisenda · Barcelona"
    right:
      - text: ORCID
        href: https://orcid.org/0000-0003-0151-7872
      - text: Scholar
        href: https://scholar.google.com/citations?user=VnfHQaQAAAAJ

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: false
    page-layout: article
    smooth-scroll: true
    link-external-newwindow: true
