#!/usr/bin/env python3
"""
Fetch the full publication list from PubMed and write _auto_publications.qmd.

Run locally or in CI:
    python scripts/fetch_pubs.py

It queries NCBI E-utilities (esearch + esummary) for the author, formats each
record as a Quarto .pub div, and highlights the author's name.

Notes / limitations
-------------------
- PubMed author queries are imperfect. "Milisenda JC[Author]" is quite specific
  (uncommon surname), but review the output the first time and, if needed,
  switch to querying by ORCID via the fields below.
- NCBI asks for an email and (optionally) an API key for higher rate limits.
  Set them below or via the NCBI_EMAIL / NCBI_API_KEY environment variables.
- This script does NOT run in the Claude sandbox (no network to NCBI). It is
  meant to run on your machine or in GitHub Actions.
"""

import os
import sys
import time
import html
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET

# ---- configuration -------------------------------------------------------
AUTHOR_TERM = "Milisenda JC[Author]"      # or: "0000-0001-6338-9218[auid]" once indexed
HIGHLIGHT   = ["Milisenda JC", "Milisenda J"]   # names to bold as "you"
EMAIL       = os.environ.get("NCBI_EMAIL", "jcmilise@clinic.cat")
API_KEY     = os.environ.get("NCBI_API_KEY", "")
OUTFILE     = os.path.join(os.path.dirname(__file__), "..", "_auto_publications.qmd")
BASE        = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
# --------------------------------------------------------------------------


def _get(url):
    with urllib.request.urlopen(url, timeout=30) as r:
        return r.read()


def esearch(term, retmax=500):
    params = {"db": "pubmed", "term": term, "retmax": retmax,
              "sort": "pub_date", "email": EMAIL}
    if API_KEY:
        params["api_key"] = API_KEY
    data = _get(f"{BASE}/esearch.fcgi?{urllib.parse.urlencode(params)}")
    root = ET.fromstring(data)
    return [e.text for e in root.findall(".//Id")]


def efetch(pmids):
    """Fetch full records in batches; return list of dicts."""
    out = []
    for i in range(0, len(pmids), 100):
        chunk = pmids[i:i + 100]
        params = {"db": "pubmed", "id": ",".join(chunk),
                  "retmode": "xml", "email": EMAIL}
        if API_KEY:
            params["api_key"] = API_KEY
        data = _get(f"{BASE}/efetch.fcgi?{urllib.parse.urlencode(params)}")
        root = ET.fromstring(data)
        for art in root.findall(".//PubmedArticle"):
            out.append(_parse(art))
        time.sleep(0.34)  # be polite to NCBI
    return out


def _parse(art):
    def text(path):
        el = art.find(path)
        return el.text if el is not None and el.text else ""

    title = text(".//ArticleTitle").rstrip(".")
    journal = text(".//Journal/ISOAbbreviation") or text(".//Journal/Title")
    year = text(".//JournalIssue/PubDate/Year") or text(".//PubDate/MedlineDate")[:4]
    pmid = text(".//PMID")

    authors = []
    for a in art.findall(".//AuthorList/Author"):
        ln = a.findtext("LastName", "")
        ini = a.findtext("Initials", "")
        if ln:
            authors.append(f"{ln} {ini}".strip())
    return {"title": title, "journal": journal, "year": year,
            "pmid": pmid, "authors": authors}


def _fmt_authors(authors):
    parts = []
    for a in authors:
        label = a
        if any(a.startswith(h) or a == h for h in HIGHLIGHT):
            label = f"[**{a}**]{{.me}}"
        parts.append(label)
    if len(parts) > 12:                      # trim very long author lists
        parts = parts[:12] + ["et al."]
    return ", ".join(parts)


def main():
    print(f"Searching PubMed for: {AUTHOR_TERM}", file=sys.stderr)
    pmids = esearch(AUTHOR_TERM)
    print(f"Found {len(pmids)} records; fetching…", file=sys.stderr)
    records = efetch(pmids)
    records.sort(key=lambda r: r["year"], reverse=True)

    lines = ["<!-- AUTO-GENERATED by scripts/fetch_pubs.py — do not edit by hand -->", ""]
    current_year = None
    for r in records:
        if r["year"] != current_year:
            current_year = r["year"]
            lines.append(f"\n### {current_year}\n")
        auth = _fmt_authors(r["authors"])
        venue = f"*{r['journal']}*. {r['year']}."
        link = f"https://pubmed.ncbi.nlm.nih.gov/{r['pmid']}/"
        lines.append(
            f"::: {{.pub}}\n{auth}. "
            f"[{html.unescape(r['title'])}]({link}). "
            f"[{venue}]{{.venue}}\n:::\n"
        )

    with open(OUTFILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {len(records)} publications to {OUTFILE}", file=sys.stderr)


if __name__ == "__main__":
    main()
